#ifndef GLOBAL_H_
#define GLOBAL_H_

#define HOSTNAME_LEN 128
#define PATH_LEN 256
#define AUTHOR_COMMAND "AUTHOR"
#define IP_COMMAND "IP"
#define PORT_COMMAND "PORT"
#define LIST_COMMAND "LIST"
#define LOGIN_COMMAND "LOGIN"
#define REFRESH_COMMAND "REFRESH"
#define SEND_COMMAND "SEND"
#define BROADCAST_COMMAND "BROADCAST"
#define BLOCK_COMMAND "BLOCK"
#define BLOCKED_COMMAND "BLOCKED"
#define UNBLOCK_COMMAND "UNBLOCK"
#define LOGOUT_COMMAND "LOGOUT"
#define EXIT_COMMAND "EXIT"
#define STATISTICS_COMMAND "STATISTICS"

#endif
